export const authActionTypes = {
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGIN_FAILURE : 'LOGIN_FAILURE',
    SIGNUP_SUCCESS:'SIGNUP_SUCCESS',
    SIGNUP_FAILURE:'SIGNUP_FAILURE',
    LOG_OUT:'LOG_OUT'
}